# import from system
from typing import List, Dict

# import from app
from DBtransactions.DBtypes import Series


__all__ = ['DATA', 'fetch_info']


DATA = [

    # quantidade agregados
    {'series_id': "PREV.CONCE_TOTALQ",
     'description': "QUANTIDADE DE CONCESSOES BENEFICIOS, TOTAL"},
    {'series_id': "PREV.CONCE_URBQ",
     'description': "QUANTIDADE DE CONCESSOES BENEFICIOS, BENEFICIARIOS URBANOS"},
    {'series_id': "PREV.CONCE_RURALQ",
     'description': "QUANTIDADE DE CONCESSOES BENEFICIOS, BENEFICIARIOS RURAIS"},
    {'series_id': "PREV.CONCE_RGPSQ",
     'description': "QUANTIDADE DE CONCESSOES BENEFICIOS, BENEFICIOS DO RGPS"},
    {'series_id': "PREV.CONCE_ASSISTQ", 
     'description': "QUANTIDADE DE CONCESSOES BENEFICIOS, BENEFICIOS ASSISTENCIAS"},
    {'series_id': "PREV.CONCE_BLEQ", 
     'description': "QUANTIDADE DE CONCESSOES BENEFICIOS, BENEFICIOS DE LEGISLACAO ESPECIFICA"},
    {'series_id': "PREV.EST_TOTALQ", 
     'description': "ESTOQUE CONCESSOES BENEFICIOS, TOTAL"},
    {'series_id': "PREV.EST_URBQ", 
     'description': "ESTOQUE CONCESSOES BENEFICIOS, BENEFICIARIOS URBANOS"},
    {'series_id': "PREV.EST_RURALQ", 
     'description': "ESTOQUE CONCESSOES BENEFICIOS, BENEFICIARIOS RURAIS"},
    {'series_id': "PREV.EST_RGPSQ", 
     'description': "ESTOQUE CONCESSOES BENEFICIOS, BENEFICIOS DO RGPS"},
    {'series_id': "PREV.EST_ASSISTQ", 
     'description': "ESTOQUE CONCESSOES BENEFICIOS, BENEFICIOS DO ASSISTENCIAIS"},
    {'series_id': "PREV.EST_BLEQ",
     'description': "ESTOQUE CONCESSOES BENEFICIOS, BENEFICIOS DE LEGISLACAO ESPECIFICA"},


    #valores agregados
    {'series_id': "PREV.CONCE_TOTALV",
     'description': "VALOR DAS CONCESSOES BENEFICIOS, TOTAL"},
    {'series_id': "PREV.CONCE_URBV",
     'description': "VALOR DAS CONCESSOES BENEFICIOS, BENEFICIARIOS URBANOS"},
    {'series_id': "PREV.CONCE_RURALV",
     'description': "VALOR DAS CONCESSOES BENEFICIOS, BENEFICIARIOS RURAIS"},
    {'series_id': "PREV.CONCE_RGPSV",
     'description': "VALOR DAS CONCESSOES BENEFICIOS, BENEFICIOS DO RGPS"},
    {'series_id': "PREV.CONCE_ASSISTV", 
     'description': "VALOR DAS CONCESSOES BENEFICIOS, BENEFICIOS ASSISTENCIAS"},
    {'series_id': "PREV.CONCE_BLEV", 
     'description': "VALOR DAS CONCESSOES BENEFICIOS, BENEFICIOS DE LEGISLACAO ESPECIFICA"},
    {'series_id': "PREV.EST_TOTALV", 
     'description': "VALOR DOS ESTOQUE DAS CONCESSOES BENEFICIOS, TOTAL"},
    {'series_id': "PREV.EST_URBV", 
     'description': "VALOR DOS ESTOQUE DAS CONCESSOES BENEFICIOS, BENEFICIARIOS URBANOS"},
    {'series_id': "PREV.EST_RURALV", 
     'description': "VALOR DOS ESTOQUE DAS CONCESSOES BENEFICIOS, BENEFICIARIOS RURAIS"},
    {'series_id': "PREV.EST_RGPSV", 
     'description': "VALOR DOS ESTOQUE DAS CONCESSOES BENEFICIOS, BENEFICIOS DO RGPS"},
    {'series_id': "PREV.EST_ASSISTV", 
     'description': "VALOR DOS ESTOQUE DAS CONCESSOES BENEFICIOS, BENEFICIOS DO ASSISTENCIAIS"},
    {'series_id': "PREV.EST_BLEV",
     'description': "VALOR DOS ESTOQUE DAS CONCESSOES BENEFICIOS, BENEFICIOS DE LEGISLACAO ESPECIFICA"}, 


    # quantidade desagregados mensal
    {'series_id': "PREV.CONCE_RGPSP_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, TOTAL DOS BENEFICIOS PREVIDENCIARIOS DO RGPS"},

    {'series_id': "PREV.CONCE_RGPSPA_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, TOTAL DAS APONSENTADORIAS PREVIDENCIARIOS DO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPAI_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, APONSETADORIAS PREVIDENCIARIOS POR IDADE DO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPAIN_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, APONSETADORIAS PREVIDENCIARIOS POR INVALIDEZ DO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPAT_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, APONSETADORIAS PREVIDENCIARIOS POR TEMPO DE CONTRIBUICAO DO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPPM_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, PENSOES DE MORTE EMITIDAS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPAUX_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, TOTAL DOS AUXILIOS PREVIDENCIARIOS EMITIDOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPAUXD_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, AUXILIOS DOENCA PREVIDENCIARIOS EMITIDOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPAUXA_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, AUXILIOS ACIDENTE PREVIDENCIARIOS EMITIDOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPAUXR_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, AUXILIOS RECLUSAO PREVIDENCIARIOS EMITIDOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPSM_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, SALARIOS MATERNIDADE PREVIDENCIARIOS EMITIDOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPACC_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, TOTAL DE PENSOES POR ACIDENTES EMITIDAS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPACCI_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, PENSAO POR ACIDENTES E INVALIDEZ EMITIDAS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPACCM_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, PENSAO POR MORTE DEVIDO A ACIDENTES EMITIDAS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPACCD_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, PENSAO POR DOENÇA DEVIDO A ACIDENTES EMITIDAS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPACCA_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, AUXILIO ACIDENTE POR CONTIGENCIAS EMIIDOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPACCS_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, AUXILIO SUPLEMENTAR POR ACIDENTES EMITIDOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSBF_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, TOTAL BENIFICIOS ASSISTENCIAS EMITOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSBFlOAS_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, TOTAL BENIFICIOS ASSISTENCIAS DOS LOAS EMITOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSBFlOASI_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, TOTAL BENIFICIOS ASSISTENCIAS DOS LOAS A IDOSOS EMITOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSBFLOASPD_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, TOTAL BENIFICIOS ASSISTENCIAS DOS LOAS A PORTADORES DE DEFINCIENCIA EMITOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSBLE_PREVQ",
     'description': "QUANTIDADE DE CONCESSOES DE BENEFICIOS, TOTAL BENIFICIOS DE LEGISLACAO ESPECIFICA EMITOS PELO RGPS"},

    # valor desagregados mensal
    {'series_id': "PREV.CONCE_RGPSP_PREVV",
     'description': "VALOR DE CONCESSOES DE BENEFICIOS, TOTAL DOS BENEFICIOS PREVIDENCIARIOS DO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPA_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, TOTAL DAS APONSENTADORIAS PREVIDENCIARIOS DO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPAI_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, APONSETADORIAS PREVIDENCIARIOS POR IDADE DO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPAIN_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, APONSETADORIAS PREVIDENCIARIOS POR INVALIDEZ DO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPAT_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, APONSETADORIAS PREVIDENCIARIOS POR TEMPO DE CONTRIBUICAO DO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPPM_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, PENSOES DE MORTE EMITIDAS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPAUX_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, TOTAL DOS AUXILIOS PREVIDENCIARIOS EMITIDOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPAUXD_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, AUXILIOS DOENCA PREVIDENCIARIOS EMITIDOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPAUXA_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, AUXILIOS ACIDENTE PREVIDENCIARIOS EMITIDOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPAUXR_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, AUXILIOS RECLUSAO PREVIDENCIARIOS EMITIDOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPSM_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, SALARIOS MATERNIDADE PREVIDENCIARIOS EMITIDOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPACC_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, TOTAL DE PENSOES POR ACIDENTES EMITIDAS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPACCI_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, PENSAO POR ACIDENTES E INVALIDEZ EMITIDAS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPACCM_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, PENSAO POR MORTE DEVIDO A ACIDENTES EMITIDAS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPACCD_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, PENSAO POR DOENÇA DEVIDO A ACIDENTES EMITIDAS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPACCA_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, AUXILIO ACIDENTE POR CONTIGENCIAS EMIIDOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSACCS_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, AUXILIO SUPLEMENTAR POR ACIDENTES EMITIDOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSPBF_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, TOTAL BENIFICIOS ASSISTENCIAS EMITOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSBFlOAS_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, TOTAL BENIFICIOS ASSISTENCIAS DOS LOAS EMITOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSBFlOASI_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, TOTAL BENIFICIOS ASSISTENCIAS DOS LOAS A IDOSOS EMITOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSBFLOASPD_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, TOTAL BENIFICIOS ASSISTENCIAS DOS LOAS A PORTADORES DE DEFINCIENCIA EMITOS PELO RGPS"},
    {'series_id': "PREV.CONCE_RGPSBLE_PREVV",
     'description': "VALOR DA NOVAS CONCESSOES DE BENEFICIOS, TOTAL BENIFICIOS DE LEGISLACAO ESPECIFICA EMITOS PELO RGPS"}
]





    
def fetch_info(series: List[Dict[str, str]]):
    for s in series:
        s['frequency'] = 'MENSAL'
        s['last_update'] = ''
        s['survey_id'] = 'PREV_EST'
    return [Series(**s) for s in series]
