#############################################
# Data from http://www.ipeadata.gov.br/api/ 
#############################################

# import from system
from concurrent.futures import ThreadPoolExecutor as executor
import time
from typing import List, Dict

#import from packages
import requests
import pandas as pd

__all__ = ["tickers_ipea", "fetch_info"]

#app imports
# from DB.transactions import add_series

URL = "http://www.ipeadata.gov.br/api/odata4/"

# series to be fetched from api
tickers_ipea = ["ABPO12_PAPEL12",
                "ANDA_PFERTILIZ",
                "ANDA12_PFERTILIZ12",
                "ANDA_VFERTILIZ",
           "ANDA12_VFERTILIZ12",
           "ANDA_MFERTILIZ",
           "ANDA12_MFERTILIZ12",
           "ANFAVE_QVEICL",
           "ANFAVE12_LICVEN12",
           "ANFAVE12_QCAMINM12",
           "ANFAVE12_QONIBUM12",
           "ANFAVE12_QPASSAM12",
           "ANFAVE12_QVEICLM12",
           "ANFAVE12_QVETOTM12",
           "ANFAVE12_LICCAMINM12",
           "ANFAVE12_LICCAMINN12",
           "ANFAVE12_LICCAMINTOT12",
           "ANFAVE12_LICNCL12",
           "ANFAVE12_LICNONI12",
           "ANFAVE12_LICONIM12",
           "ANFAVE12_LICONITOT12",
           "ANFAVE12_LICPASSAMM12",
           "ANFAVE12_LICPASSAMN12",
           "ANFAVE12_LICPASSAMTOT12",
           "ANFAVE12_LICVEM12",
           "ANFAVE12_LICVETOT12",
           "ANFAVE12_XCAMINM12",
           "ANFAVE12_XONIBUM12",
           "ANFAVE12_XPASSAM12",
           "ANFAVE12_XVEICLM12",
           "ANFAVE12_XVETOTM12",
           "ANP12_PDGASN12",
           "ANP12_PDPET12",
           "ANP_CALCO",
           "ANP_CODP",
           "ANP12_CALCO12",
           "ANP12_CDEPET12",
           "ANP12_CGASOL12",
           "ANP12_CGLP12",
           "ANP12_CODP12",
           "ANP12_COLCOM12",
           "ANP12_COLDIE12",
           "CEF12_FGTS12",
           "SNIC12_V50KGSCC12",
           "SNIC12_VKGSCC12",
           "SNIC12_VTONSCC12",
           "ELETRO_CEECOM",
           "ELETRO_CEEIND",
           "ELETRO_CEEOUT",
           "ELETRO_CEERES",
           "ELETRO_CEET",
           "ELETRO_CEETCOM",
           "ELETRO_CEETIND",
           "ELETRO_CEETRES",
           "ELETRO_CEETT",
           "ELETRO12_CEECO12",
           "ELETRO12_CEECOM12",
           "ELETRO12_CEEIND12",
           "ELETRO12_CEENE12",
           "ELETRO12_CEENO12",
           "ELETRO12_CEEOUT12",
           "ELETRO12_CEERES12",
           "ELETRO12_CEESE12",
           "ELETRO12_CEESU12",
           "ELETRO12_CEET12",
           "FCESP12_IICA12",
           "FCESP12_IIC12",
           "FCESP12_IICF12",
           "FENABRAVE12_VENDAUTO12",
           "FENABRAVE12_VENDVETOT12",
           "CE_CUTIND",
           "CE12_CUTIND12",
           "FIPE12_TXARJ12",
           "FIPE12_TXASP12",
           "FIPE12_VENBH12",
           "FIPE12_VENBR12",
           "FIPE12_VENDF12",
           "FIPE12_VENFO12",
           "FIPE12_VENRE12",
           "FIPE12_VENRJ12",
           "FIPE12_VENSA12",
           "FIPE12_VENSP12",
           "FNDE12_SALEDU12",
           "FUNCEX_MDPBCD",
           "FUNCEX_MDPBCND",
           "FUNCEX_MDPBI",
           "FUNCEX_MDPBK",
           "FUNCEX_MDPCOMB",
           "FUNCEX_MDPT",
           "FUNCEX_MDQBCD",
           "FUNCEX_MDQBCND",
           "FUNCEX_MDQBI",
           "FUNCEX_MDQBK",
           "FUNCEX_MDQCOMB",
           "FUNCEX_MDQT",
           "FUNCEX12_MDPBCDGCE12",
           "FUNCEX12_MDPBCNDGCE12",
           "FUNCEX12_MDPBIGCE12",
           "FUNCEX12_MDPBKGCE12",
           "FUNCEX12_MDPCOMBGCE12",
           "FUNCEX12_MDPT12",
           "FUNCEX12_MDQBCDGCE12",
           "FUNCEX12_MDQBCNDGCE12",
           "FUNCEX12_MDQBIGCE12",
           "FUNCEX12_MDQBKGCE12",
           "FUNCEX12_MDQCOMBGCE12",
           "FUNCEX12_MDQT12",
           "FUNCEX12_MPAGP2N12",
           "FUNCEX12_MPAL2N12",
           "FUNCEX12_MPBEB2N12",
           "FUNCEX12_MPCAL2N12",
           "FUNCEX12_MPDIV2N12",
           "FUNCEX12_MPEMM2N12",
           "FUNCEX12_MPEMNM2N12",
           "FUNCEX12_MPEPET2N12",
           "FUNCEX12_MPFARM2N12",
           "FUNCEX12_MPFUMO2N12",
           "FUNCEX12_MPIMPG2N12",
           "FUNCEX12_MPMAD2N12",
           "FUNCEX12_MPMAQELET2N12",
           "FUNCEX12_MPMAQEQU2N12",
           "FUNCEX12_MPMAQINF2N12",
           "FUNCEX12_MPMET2N12",
           "FUNCEX12_MPMETBAS2N12",
           "FUNCEX12_MPMNM2N12",
           "FUNCEX12_MPMOV2N12",
           "FUNCEX12_MPOUTTRANS2N12",
           "FUNCEX12_MPPAP2N12",
           "FUNCEX12_MPPES2N12",
           "FUNCEX12_MPPETCOMB2N12",
           "FUNCEX12_MPPLAS2N12",
           "FUNCEX12_MPPRF2N12",
           "FUNCEX12_MPQUIM2N12",
           "FUNCEX12_MPTEXT2N12",
           "FUNCEX12_MPVEIC2N12",
           "FUNCEX12_MPVEST2N12",
           "FUNCEX12_MQAGP2N12",
           "FUNCEX12_MQAL2N12",
           "FUNCEX12_MQBEB2N12",
           "FUNCEX12_MQCAL2N12",
           "FUNCEX12_MQDIV2N12",
           "FUNCEX12_MQEMM2N12",
           "FUNCEX12_MQEMNM2N12",
           "FUNCEX12_MQEPET2N12",
           "FUNCEX12_MQFARM2N12",
           "FUNCEX12_MQFUMO2N12",
           "FUNCEX12_MQIMQG2N12",
           "FUNCEX12_MQMAD2N12",
           "FUNCEX12_MQMAQELET2N12",
           "FUNCEX12_MQMAQEQU2N12",
           "FUNCEX12_MQMAQINF2N12",
           "FUNCEX12_MQMET2N12",
           "FUNCEX12_MQMETBAS2N12",
           "FUNCEX12_MQMNM2N12",
           "FUNCEX12_MQMOV2N12",
           "FUNCEX12_MQOUTTRANS2N12",
           "FUNCEX12_MQPAP2N12",
           "FUNCEX12_MQPES2N12",
           "FUNCEX12_MQPETCOMB2N12",
           "FUNCEX12_MQPLAS2N12",
           "FUNCEX12_MQPRF2N12",
           "FUNCEX12_MQQUIM2N12",
           "FUNCEX12_MQTEXT2N12",
           "FUNCEX12_MQVEIC2N12",
           "FUNCEX12_TTR12",
           "FUNCEX12_XPAGP2N12",
           "FUNCEX12_XPAL2N12",
           "FUNCEX12_XPB12",
           "FUNCEX12_XPBCDGCE12",
           "FUNCEX12_XPBCNDGCE12",
           "FUNCEX12_XPBEB2N12",
           "FUNCEX12_XPBIGCE12",
           "FUNCEX12_XPBKGCE12",
           "FUNCEX12_XPCAL2N12",
           "FUNCEX12_XPCOMBGCE12",
           "FUNCEX12_XPDIV2N12",
           "FUNCEX12_XPEMM2N12",
           "FUNCEX12_XPEMNM2N12",
           "FUNCEX12_XPEPET2N12",
           "FUNCEX12_XPFARM2N12",
           "FUNCEX12_XPFUMO2N12",
           "FUNCEX12_XPIXPG2N12",
           "FUNCEX12_XPM12",
           "FUNCEX12_XPMAD2N12",
           "FUNCEX12_XPMAQELET2N12",
           "FUNCEX12_XPMAQEQU2N12",
           "FUNCEX12_XPMAQINF2N12",
           "FUNCEX12_XPMET2N12",
           "FUNCEX12_XPMETBAS2N12",
           "FUNCEX12_XPMNM2N12",
           "FUNCEX12_XPMOV2N12",
           "FUNCEX12_XPOUTTRANS2N12",
           "FUNCEX12_XPPAP2N12",
           "FUNCEX12_XPPES2N12",
           "FUNCEX12_XPPETCOMB2N12",
           "FUNCEX12_XPPLAS2N12",
           "FUNCEX12_XPPRF2N12",
           "FUNCEX12_XPQUIM2N12",
           "FUNCEX12_XPS12",
           "FUNCEX12_XPT12",
           "FUNCEX12_XPTEXT2N12",
           "FUNCEX12_XPVEIC2N12",
           "FUNCEX12_XPVEST2N12",
           "FUNCEX12_XQAGP2N12",
           "FUNCEX12_XQAL2N12",
           "FUNCEX12_XQB12",
           "FUNCEX12_XQBCDGCE12",
           "FUNCEX12_XQBCNDGCE12",
           "FUNCEX12_XQBEB2N12",
           "FUNCEX12_XQBIGCE12",
           "FUNCEX12_XQBKGCE12",
           "FUNCEX12_XQCAL2N12",
           "FUNCEX12_XQCOMBGCE12",
           "FUNCEX12_XQDIV2N12",
           "FUNCEX12_XQEMM2N12",
           "FUNCEX12_XQEMNM2N12",
           "FUNCEX12_XQEPET2N12",
           "FUNCEX12_XQFARM2N12",
           "FUNCEX12_XQFUMO2N12",
           "FUNCEX12_XQIXQG2N12",
           "FUNCEX12_XQM12",
           "FUNCEX12_XQMAD2N12",
           "FUNCEX12_XQMAQELET2N12",
           "FUNCEX12_XQMAQEQU2N12",
           "FUNCEX12_XQMAQINF2N12",
           "FUNCEX12_XQMET2N12",
           "FUNCEX12_XQMETBAS2N12",
           "FUNCEX12_XQMNM2N12",
           "FUNCEX12_XQMOV2N12",
           "FUNCEX12_XQOUTTRANS2N12",
           "FUNCEX12_XQPAP2N12",
           "FUNCEX12_XQPES2N12",
           "FUNCEX12_XQPETCOMB2N12",
           "FUNCEX12_XQPLAS2N12",
           "FUNCEX12_XQPRF2N12",
           "FUNCEX12_XQQUIM2N12",
           "FUNCEX12_XQS12",
           "FUNCEX12_XQT12",
           "FUNCEX12_XQTEXT2N12",
           "FUNCEX12_XQVEIC2N12",
           "FUNCEX12_XQVEST2N12",
           "FUNCEX12_XR12",
           "FUNCEX12_XVOUTTRANS2N12",
           "FUNCEX12_XVPAP2N12",
           "IBSIE_QSCAB",
           "IBSIE_QSCFG",
           "IBSIE_QSCL",
           "IBSIE12_QSCAB12",
           "IBSIE12_QSCFG12",
           "IBSIE12_QSCL12",
           "GAC12_FBKFCAMI12",
           "GAC12_FBKFCAMIDESSAZ12",
           "GAC12_INDFBCF12",
           "GAC12_INDFBCFCC12",
           "GAC12_INDFBCFCCDESSAZ12",
           "GAC12_INDFBCFDESSAZ12",
           "DIMAC_INF1",
           "DIMAC_INF2",
           "DIMAC_INF3",
           "DIMAC_INF4",
           "DIMAC_INF5",
           "DIMAC_INF6",
           "PAN4_FBKFI90G4",
           "PAN4_FBKFPIBV4",
           "PAN4_TCERXTINPC4",
           "DIMAC_DCONSTNRESDE",
           "DIMAC_DCONSTNRESINF",
           "DIMAC_DCONSTRES",
           "DIMAC_DCONSTTOT",
           "DIMAC_DEFBRUTINF",
           "DIMAC_DMAQE",
           "DIMAC_DOUT",
           "DIMAC_DTOT",
           "DIMAC_ECFLIQCONSTNRESDE",
           "DIMAC_ECFLIQCONSTNRESINF",
           "DIMAC_ECFLIQCONSTRES",
           "DIMAC_ECFLIQCONSTTOT",
           "DIMAC_ECFLIQMAQE",
           "DIMAC_ECFLIQOUT",
           "DIMAC_ECFLIQTOT",
           "DIMAC_ECFLIQTOT12",
           "DIMAC_ECFLIQTOT4",
           "DIMAC_ILIQTOT112",
           "DIMAC_TDICONSTNRESDE",
           "DIMAC_TDICONSTNRESINF",
           "DIMAC_TDICONSTRES",
           "DIMAC_TDICONSTTOT",
           "DIMAC_TDIMAQE",
           "DIMAC_TDIOUT",
           "DIMAC_TDITOT",
           "JPM366_EMBI366",
           "SECEX12_XGASOL12",
           "SECEX12_XGASOLKG12",
           "MME_CAPINSTEE",
           "MME_HIDRAU",
           "MME_NUCLEAR",
           "MME_PENREC",
           "MME_PENRECM",
           "MME_PENREGN",
           "MME_PENREP",
           "MME_PENRETOT",
           "MME_PENREU",
           "MME_PERECA",
           "MME_PEREHIDR",
           "MME_PEREL",
           "MME_PEREOUT",
           "MME_PERETOT",
           "MME_PETOT",
           "MME_TERMICA",
           "MME_CEAGRO",
           "MME_CECOM",
           "MME_CEENE",
           "MME_CEIND",
           "MME_CENE",
           "MME_CENID",
           "MME_CEPUBL",
           "MME_CERES",
           "MME_CETOT",
           "MME_CETRANS",
           "ONS12_CONV12",
           "ONS12_HIDR12",
           "ONS12_NUCL12",
           "DERAL12_ATARP12",
           "DERAL12_ATARPO12",
           "DERAL12_ATBCAD12",
           "DERAL12_ATBCAT12",
           "DERAL12_ATBSUI12",
           "DERAL12_ATCAM12",
           "DERAL12_ATFEC12",
           "DERAL12_ATFECU12",
           "DERAL12_ATFEP12",
           "DERAL12_ATFMAC12",
           "DERAL12_ATFMAT12",
           "DERAL12_ATFMP12",
           "DERAL12_ATFRC12",
           "DERAL12_ATFRM12",
           "DERAL12_ATFRR12",
           "DERAL12_ATFSO12",
           "DERAL12_ATFTRC12",
           "DERAL12_ATFTRE12",
           "DERAL12_ATFUA12",
           "DERAL12_ATMAE12",
           "DERAL12_ATMC12",
           "DERAL12_ATOLB12",
           "DERAL12_ATOLR12",
           "DERAL12_ATOVE12",
           "DERAL12_ATOVG12",
           "DERAL12_ATOVM12",
           "DERAL12_ATPIC12",
           "DERAL12_ATPIP12",
           "DERAL12_ATQMF12",
           "DERAL12_ATQMZ12",
           "DERAL12_ATQPA12",
           "DERAL12_ATQPR12",
           "DERAL12_ATSCAR12",
           "DERAL12_ATSULO12",
           "DERAL12_ATSUPA12",
           "DERAL12_ATSUPE12",
           "DERAL12_ATTRG12",
           "DERAL12_PRARIR12",
           "DERAL12_PRARSE12",
           "DERAL12_PRBGO12",
           "DERAL12_PRBMA12",
           "DERAL12_PRCAN12",
           "DERAL12_PRCCO12",
           "DERAL12_PRFEC12",
           "DERAL12_PRFEP12",
           "DERAL12_PRFRV12",
           "DERAL12_PRLECO12",
           "DERAL12_PRMAN12",
           "DERAL12_PRMI12",
           "DERAL12_PROVG12",
           "DERAL12_PROVM12",
           "DERAL12_PRSO12",
           "DERAL12_PRSUC12",
           "DERAL12_PRTRG12",
           "SNIC12_QSCC12",
           "SNIC12_QCASCC12",
           "SNIC12_QDSCC12"]
    

def build_url(tck:str) -> str:
    """
    builds the url to fetch the metadados of a series 
    from ipeadatas webpage. 
    """
    return URL + f"Metadados('{tck}')"
    

def process(resp:requests.models.Response) ->  Dict:
    """
    handles a response of a request to the ipea's ipea for
    metadados for a particular seires.
    """
    if resp.ok:
        js = resp.json()['value'][0]
        d = dict([(k, js[k]) for k in ('SERCODIGO', 'SERNOME', 'FNTSIGLA', "PERNOME")])
        d["Survey"] = 'IPEA_FIN' if d['SERCODIGO'] == 'JPM366_EMBI366' else 'IPEA_ECON'
        d["SERCODIGO"] = f"IPEA.{d['SERCODIGO']}" 
        d["SERNOME"] = f"{d['SERNOME']}" + f", { d['PERNOME'] if d['PERNOME'].upper() else ''}"
        d["SERNOME"] = f"{d['SERNOME']}" + f", { d['FNTSIGLA'] if d['FNTSIGLA'].upper() else ''}"
        d.pop('PERNOME')
        d.pop('FNTSIGLA')
        return d
    else:
        print(f"Could not reach {resp.url}")


def fetch_info(tickers: List[str]) -> pd.DataFrame:
    """
    takes a list of tickers (without prefix IPEA),
    fetches meta information on them from IPEA api and 
    then inserts that information in the datebase
    """
    t0=time.time()
    urls =[build_url(tck) for tck in tickers]
    with requests.session() as session:
        with executor() as e:
            ljs = list(e.map(lambda u: process(session.get(u)), urls))
            
    df = pd.DataFrame(data=ljs)
    df.columns = ['series_id', 'description', 'survey']
    return df


